---
- name: Atualizar cache do APT
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Garantir que HAProxy esteja habilitado
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started


- name: Configurar HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    validate: 'haproxy -c -f %s'
  notify: Reiniciar HAProxy